### ISSUE TITLE
NPE soft crash in 1.12

### ISSUE THREAD

**Issue by SDPhantom** [squeek502/WailaHarvestability#61]
Versions:
Minecraft 1.12.1
Forge-1.12.1-14.22.1.2480
Hwyla-1.8.20-B35_1.12
Wawla-1.12.1-2.5.243
WailaHarvestability-mc1.12-1.1.11

Occasionally while looking over a block, the tooltip reads "&lt;ERROR&gt;" where the harvest data should be. It only seems to occur while holding a tool. So far, I've only tested this with vanilla tools and in minimal mode. It doesn't happen 100% of the time, but is fairly often.

This stacktrace appears in WailaErrorOutput.txt
`09/18/2017 - 11:49:15
class squeek.wailaharvestability.WailaHandler
java.lang.NullPointerException
	at net.minecraft.item.ItemTool.getHarvestLevel(ItemTool.java:124)
	at squeek.wailaharvestability.helpers.ToolHelper.canToolHarvestLevel(ToolHelper.java:40)
	at squeek.wailaharvestability.WailaHandler.getHarvestability(WailaHandler.java:121)
	at squeek.wailaharvestability.WailaHandler.getWailaBody(WailaHandler.java:62)
	at mcp.mobius.waila.api.impl.MetaDataProvider.handleBlockTextData(MetaDataProvider.java:120)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_459_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:347)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1909)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by squeek502** [comment]
Thanks, someone reported this same error to me on Curse a few days ago, but I haven't figured it out. Any specific blocks that trigger it for you?

**Comment by squeek502** [comment]
Nevermind, figured it out. Will release a fixed version in a bit.

**Comment by squeek502** [comment]
Should be fixed in v1.1.12:
- https://minecraft.curseforge.com/projects/waila-harvestability/files
- https://github.com/squeek502/WailaHarvestability/releases/tag/v1.1.12
